In [1]:
import pandas as pd

In [2]:
frozenfish = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22',"2022-23"],'Quantity': [100093,173005,188029,108556,131304,212903,174976,196322,138023,159689,182344,270751,220200,238544,260979,312358,347118,343876,324359,309434,228749,296762,353192,338933,223318,188130,226586,368549],
        'Price': [372.26,636.92,726.73,495.03,537.34,874.68,713.11,841.65,620.73,759.27,998.7,1452.88,1303.41,1722.34,2032.33,2623.89,3284.15,3296.86,4294.81,3778.5,3462.25,4460.9,4674.03,4916.82,3610.01,2941.65,3471.91,5503.1]}


In [3]:
df=pd.DataFrame(frozenfish)
df

,Year,Quantity,Price
0,1995-96,100093,372.26
1,1996-97,173005,636.92
2,1997-98,188029,726.73
3,1998-99,108556,495.03
4,1999-00,131304,537.34
5,2000-01,212903,874.68
6,2001-02,174976,713.11
7,2002-03,196322,841.65
8,2003-04,138023,620.73
9,2004-05,159689,759.27


In [4]:
# objective 2

In [5]:
from statsmodels.tsa.stattools import coint

In [6]:
# Extract the 'price' and 'quantity' columns
price = frozenfish['Price']
quantity = frozenfish['Quantity']


In [7]:
# Perform the cointegration test
result = coint(price, quantity)
result

(-1.9195379242969848,
 0.5700655466231038,
 array([-4.34805632, -3.5717894 , -3.20526262]))

In [8]:
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]

In [9]:
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')


Cointegration Test Statistic: -1.9195379242969848
p-value: 0.5700655466231038


In [10]:
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


There is no evidence of cointegration between fish export price and quantity.


# data

In [11]:


import pandas as pd
frozenshrimp = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],'Quantity': [95724,105427,101318,102484,110275,111874,127709,134815,129768,138085,145180,137397,136223,126039,130553,151465,189125,228620,301435,357505,373866,434486,565980,614145,652253,590275,728123],
'Price': [2356.81,2701.76,3140.56,3344.91,3645.22,4481.51,4139.92,4608.31,4013.07,4220.67,4271.51,4506.08,3941.62,3779.8,4182.35,5718.13,8175.26,9706.36,19368.3,22468.12,20045.5,24711.32,30868.17,31800.51,34152.03,32525.29,42706.04]}
df1=pd.DataFrame(frozenshrimp)


In [12]:
import pandas as pd
frozenfish = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],
        'Quantity': [100093,173005,188029,108556,131304,212903,174976,196322,138023,159689,182344,270751,220200,238544,260979,312358,347118,343876,324359,309434,228749,296762,353192,338933,223318,188130,226586],
        'Price': [372.26,636.92,726.73,495.03,537.34,874.68,713.11,841.65,620.73,759.27,998.7,1452.88,1303.41,1722.34,2032.33,2623.89,3284.15,3296.86,4294.81,3778.5,3462.25,4460.9,4674.03,4916.82,3610.01,2941.65,3471.91]}
df2=pd.DataFrame(frozenfish)

In [13]:
import pandas as pd
fr_squid = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],
        'Quantity': [45025,40924,35095,32254,34918,37628,39790,37838,37832,48124,52352,47252,34172,57125,61445,87579,77373,75387,87437,69569,81769,99348,100845,101101,87631,61176,75750],
        'Price': [319.58,290.45,270.89,268.93,296.8,324.43,329.67,384.37,372.92,477.26,575.52,568.32,408.42,632.35,622.63,1010.57,1228.19,1378.08,1731.97,1275.25,1615.21,2575.29,2451.87,2506.99,2196.59,1998.9,2806.9]}
df3=pd.DataFrame(fr_squid)


In [14]:
import pandas as pd
fr_cuttle_fish = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],
        'Quantity': [33845,31778,37258,34589,32799,33677,30568,41381,39610,44239,49651,55701,45955,50750,63504,
59159,54671,63296,68577,82353,65596,63320,69183,60210,70906,59292,58992],
        'Price': [260.86,272.37,323.41,273.31,286.22,288.99,280.07,417.09,435.17,474.01,549.15,797.37,744.13,761.05,923.83,1104.57,1346.72,1354.28,1386.98,1833.21,1636.11,1944.5,2356.46,1975.97,2009.79,1626.34,2062.63]}
df4=pd.DataFrame(fr_cuttle_fish)

In [15]:
import pandas as pd
dried_fish = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],
        'Quantity': [7506,9893,5840,6320,6853,7532,8307,8178,12574,9692,14167,24293,22414,31688,47053,79059,53721,72953,67901,70544,43320,61071,88997,95296,84417,85661,73679],
'Price': [44.97,42.67,34.85,40.51,44.33,70.22,67.96,84.23,145.68,121.01,132.56,183.16,258.88,420.75,981.11,954.94,562.65,819.9,998,1010.16,725.58,871.74,1042.37,1323.45,981.5,1148.38,1472.98]}
df5=pd.DataFrame(dried_fish)

In [16]:
import pandas as pd
live_fish = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22','2022-23'],
        'Quantity': [1756,2030,1700,2148,1678,1844,1628,2115,2341,2262,2568,2478,2498,3434,5492,5208,4199,4373,5080,5488,5493,6703,7034,10179,7287,4379,7032,7824],
             'Price':[21.31,33.97,29.34,47.08,37.99,39.88,40.57,53.66,51.1,50.75,61.71,64.06,69.07,99,139.14,142.15,154.61,197.89,281.85,301.51,308.81,403.75,286.11,388.88,324.26,239.69,353.36,440.06]}
df6=pd.DataFrame(live_fish)

In [17]:
import pandas as pd
chilled_fish = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],
        'Quantity': [2773,1578,3183,2624,3088,3820,3284,3350,3779,3988,5060,7200,6541,21453,28817,21118,21278,26868,19755,31404,33150,31815,19501,17207,21202,17622,21689],
'Price':[26.08,18.74,44.31,29.18,44.97,71.63,63.66,59.14,64.03,68.14,81.56,117.3,118.11,217.34,264.49,257.54,357.42,537.11,527.84,635.93,809.5,769.81,647.41,616.22,631.84,477.99,733.47]}
df7=pd.DataFrame(chilled_fish)

In [18]:
import pandas as pd
other_fish = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],
        'Quantity':[9555,13563,13395,13960,22116,31195,38209,43299,48090,55250,60841,67571,73698,73801,80592,97145,114538,112841,109212,124947,113949,141442,172512,155487,142638,142806,177414],
        'Price':[99.24,124.48,127.39,127.91,223.81,292.54,322.09,432.88,389.23,475.58,574.58,674.35,777.29,975.33,902.64,1089.67,1488.24,1565.78,1623.5,2138.94,1817.87,2133.59,2780.48,3060.53,2756.84,2764.02,3979.99]}        
df8=pd.DataFrame(other_fish)

In [19]:
import pandas as pd
Total = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22','2022-23'],'Quantity':[296277,378199,385818,302934,343031,440473,424470,467297,412017,461329,512164,612641,541701,602835,678436,813091,862021,928215,983756,1051243,945892,1134948,1377244,1392559,1289651,1149510,1369264,1735286],
'Price':[3501.11,4121.36,4697.48,4626.86,5116.67,6443.89,5957.05,6881.31,6091.95,6646.69,7245.30,8363.53,7620.92,8607.94,10048.53,12901.47,16597.23,18856.26,30213.26,33441.61,30420.83,37870.90,45106.89,46589.37,46662.85,43720.98,57586.48,63969.14]}
df9=pd.DataFrame(Total)

In [20]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = frozenfish['Price']
quantity = frozenfish['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -1.5875492504898794
p-value: 0.7261165093509402
There is no evidence of cointegration between fish export price and quantity.


In [21]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = frozenshrimp ['Price']
quantity = frozenshrimp ['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -2.9106124859529543
p-value: 0.13301037696260237
There is no evidence of cointegration between fish export price and quantity.


In [22]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = fr_squid ['Price']
quantity = fr_squid ['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -2.6016436723222247
p-value: 0.23616815550565928
There is no evidence of cointegration between fish export price and quantity.


In [23]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = fr_cuttle_fish ['Price']
quantity = fr_cuttle_fish ['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -0.8626704977005398
p-value: 0.925954823869821
There is no evidence of cointegration between fish export price and quantity.


In [24]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = dried_fish  ['Price']
quantity = dried_fish  ['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -4.724771773308306
p-value: 0.0005109214779080388
There is evidence of cointegration between fish export price and quantity.


In [25]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = live_fish ['Price']
quantity = live_fish ['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -3.242490117240244
p-value: 0.0631047983278703
There is no evidence of cointegration between fish export price and quantity.


In [26]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = chilled_fish ['Price']
quantity = chilled_fish ['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -1.3521831713813295
p-value: 0.8134332050411615
There is no evidence of cointegration between fish export price and quantity.


In [27]:
from statsmodels.tsa.stattools import coint
# Extract the 'price' and 'quantity' columns
price = other_fish ['Price']
quantity = other_fish ['Quantity']
# Perform the cointegration test
result = coint(price, quantity)
result
# Access the test statistic and p-value from the result
test_statistic = result[0]
p_value = result[1]
# Print the cointegration test results
print(f'Cointegration Test Statistic: {test_statistic}')
print(f'p-value: {p_value}')
# Interpret the results
if p_value < 0.05:
    print("There is evidence of cointegration between fish export price and quantity.")
else:
    print("There is no evidence of cointegration between fish export price and quantity.")


Cointegration Test Statistic: -2.2477629772089593
p-value: 0.39988722216666683
There is no evidence of cointegration between fish export price and quantity.


In [28]:
import pandas as pd
import numpy as np
import statsmodels.api as sm


# Extract the two variables
variable1 = df2['Quantity_diff']
variable2 = df2['Price_diff']

# Step 1: Perform ADF test to check for unit roots

# Augmented Dickey-Fuller test on variable 1
adf_result1 = sm.tsa.stattools.adfuller(variable1)
adf_stat1 = adf_result1[0]
p_value1 = adf_result1[1]
critical_values1 = adf_result1[4]

# Augmented Dickey-Fuller test on variable 2
adf_result2 = sm.tsa.stattools.adfuller(variable2)
adf_stat2 = adf_result2[0]
p_value2 = adf_result2[1]
critical_values2 = adf_result2[4]

# Check if variables are stationary (reject null hypothesis of unit root)
print(f'p_value1: {p_value1}')
print(f'p_value2: {p_value2}')

if p_value1 > 0.05 and p_value2 > 0.05:
    print("Variables are not stationary. Cannot proceed with Engel-Granger Two-Step procedure.")
else:    
    print("Variables are stationary. Proceeding to Step 2.")


KeyError: 'Quantity_diff'

# Johansans test for Cointegraion 

In [29]:
import pandas as pd
frozenshrimp = {'Year': ['1995-96','1996-97','1997-98','1998-99','1999-00','2000-01','2001-02','2002-03','2003-04','2004-05','2005-06','2006-07','2007-08','2008-09','2009-10','2010-11','2011-12','2012-13','2013-14','2014-15','2015-16','2016-17','2017-18','2018-19','2019-20','2020-21',
'2021-22'],'Quantity': [95724,105427,101318,102484,110275,111874,127709,134815,129768,138085,145180,137397,136223,126039,130553,151465,189125,228620,301435,357505,373866,434486,565980,614145,652253,590275,728123],
'Price': [2356.81,2701.76,3140.56,3344.91,3645.22,4481.51,4139.92,4608.31,4013.07,4220.67,4271.51,4506.08,3941.62,3779.8,4182.35,5718.13,8175.26,9706.36,19368.3,22468.12,20045.5,24711.32,30868.17,31800.51,34152.03,32525.29,42706.04]}
df1=pd.DataFrame(frozenshrimp)


In [30]:
import pandas as pd
import numpy as np
from statsmodels.tsa.vector_ar.vecm import coint_johansen, VECM

# Extract the variables
variables = df2[[ 'Quantity','Price']]

# Perform Johansen cointegration test
coint_result = coint_johansen(variables, det_order=-1, k_ar_diff=1)

# Extract the cointegrating vectors
coint_vectors = coint_result.evec

# Specify the number of cointegrating vectors to use for prediction
num_coint_vectors = 1

# Create the VECM model using the cointegrating vectors
model = VECM(variables, k_ar_diff=1, coint_rank=num_coint_vectors, deterministic='nc')
model_fit = model.fit()
print(model_fit)
# Generate predictions for the next 'n' steps
n = 10
forecast = model_fit.predict(steps=10)

# Print the forecasted values
print("Forecasted Values:")
print(forecast)
model_fit.predict(10, 0.05)

Forecasted Values:
[[231888.35818433   3506.63981903]
 [230432.2546017    3561.75610179]
 [231055.28478815   3608.32806021]
 [231049.38383145   3654.57526166]
 [231222.84462534   3698.17966694]
 [231334.99488273   3739.95735035]
 [231457.96282998   3779.78407383]
 [231570.5789527    3817.81058644]
 [231679.48093522   3854.10045231]
 [231782.99917548   3888.73829141]]


(array([[231888.35818433,   3506.63981903],
        [230432.2546017 ,   3561.75610179],
        [231055.28478815,   3608.32806021],
        [231049.38383145,   3654.57526166],
        [231222.84462534,   3698.17966694],
        [231334.99488273,   3739.95735035],
        [231457.96282998,   3779.78407383],
        [231570.5789527 ,   3817.81058644],
        [231679.48093522,   3854.10045231],
        [231782.99917548,   3888.73829141]]),
 array([[132731.86768166,   2538.51591424],
        [ 90143.0855404 ,   2188.52536934],
        [ 59368.35832021,   1897.8560569 ],
        [ 32755.60565697,   1644.64745682],
        [  9443.02473646,   1410.0622934 ],
        [-11730.41040084,   1188.04106204],
        [-31221.3324287 ,    974.18854132],
        [-49400.44048764,    766.10811295],
        [-66502.35283379,    562.17327342],
        [-82704.69831642,    361.32751167]]),
 array([[331044.848687  ,   4474.76372383],
        [370721.423663  ,   4934.98683424],
        [402742.21125608,   

In [31]:
vecm = VECM(endog = X_train, k_ar_diff = 9, coint_rank = 3, deterministic = ‘ci’)
vecm_fit = vecm.fit()
vecm_fit.predict(steps=10)

SyntaxError: invalid character in identifier (<ipython-input-31-14f7189bbe9e>, line 1)

In [32]:
forecast, lower, upper = vecm_fit.predict(10, 0.05)
print(“lower bounds of confidence intervals:”)
print(lower.round(3))
print(“\npoint forecasts:”)
print(forecast.round(3))
print(“\nupper bounds of confidence intervals:”)
print(upper.round(3))

SyntaxError: invalid character in identifier (<ipython-input-32-bc0152834c70>, line 2)

In [33]:
vecm = VECM(endog=, k_ar_diff = 9, coint_rank = 3, deterministic = ‘ci’)
vecm_fit = vecm.fit()
vecm_fit.predict(steps=10)

SyntaxError: invalid syntax (<ipython-input-33-6f2fa75686f0>, line 1)

In [34]:
forecast, lower, upper = vecm_fit.predict(10, 0.05)
print(“lower bounds of confidence intervals:”)
print(lower.round(3))
print(“\npoint forecasts:”)
print(forecast.round(3))
print(“\nupper bounds of confidence intervals:”)
print(upper.round(3))

SyntaxError: invalid character in identifier (<ipython-input-34-bc0152834c70>, line 2)

In [36]:
import numpy as np
import pandas as pd
import statsmodels.api as sm

# Step 1: Check for cointegration (assuming you have already performed this step)

# Step 2: Determine the lag order (manually select or use a selection criterion)

# Step 3: Estimate the cointegration equation
# Assuming you have two time series 'x' and 'y'

# Sample data (replace this with your own data)
variables=df1[['Quantity','Price']]
# Add a constant term to the independent variable
x_with_const = sm.add_constant(df1['Quantity'])

# Fit the cointegration equation y = beta * x + epsilon
model = sm.OLS(df1['Price'], x_with_const).fit()
coint_eqn_residuals = model.resid

# Step 4: Estimate the ECM
# Assuming you have another variable 'z' to include in the ECM

# Add the differenced variables and the lagged error correction term
ecm_data = pd.DataFrame({
    'diff_x': np.diff(df1['Quantity']),
    'diff_y': np.diff(df1['Price']),
    'lagged_ec': np.roll(coint_eqn_residuals, 1)[1:]
})

# Fit the ECM: diff_y = alpha * diff_x + gamma * lagged_ec + u
ecm_model = sm.OLS(ecm_data['diff_y'], sm.add_constant(ecm_data[['diff_x', 'lagged_ec']])).fit()
print(ecm_model)
# Step 5: Evaluate the ECM (perform diagnostic tests if necessary)

# Step 6: Interpret the results
print(ecm_model.summary())


                            OLS Regression Results                            
Dep. Variable:                 diff_y   R-squared:                       0.814
Model:                            OLS   Adj. R-squared:                  0.797
Method:                 Least Squares   F-statistic:                     50.22
Date:                Tue, 27 Feb 2024   Prob (F-statistic):           4.06e-09
Time:                        20:48:31   Log-Likelihood:                -223.09
No. Observations:                  26   AIC:                             452.2
Df Residuals:                      23   BIC:                             456.0
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const       -131.7210    317.119     -0.415      0.6